name: Generate Sitemap
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # این خط جدید را اضافه کنید
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # نسخه را آپدیت کنید
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # این خط جدید را اضافه کنید
          
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://codewithbahareh.github.io/home"
          
      - name: Deploy Sitemap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap" || echo "No changes"
          git push
